### ISSUE TITLE
me sale error al ingresar

### ISSUE THREAD

**Issue by leog1992** [giansalex/Curl-Sunat#5]
Hola, Giancarlo buenas tardes, he descargado tu libreria me parece interesante hacer el curl de la bandeja de entrada de sunat  es una buena funcion, pero despues de instalar las librerias y colocar mi clave sol, me muestra error

SUNAT Operaciones en Línea
  Error en la invocación
  Ingrese nuevamente

o

Error : 56 - Failure when receiving data from the peer: OpenSSL SSL_read: Connection was reset, errno 10054

**Comment by giansalex** [comment]
Hola, esto fue hecho hace mucho tiempo, algunas cosas deben haber cambiado por lo que ya no funcionará.
